In [2]:
import numpy as np
import pandas as pd

In [3]:
# 1.查属性
arr=np.array([[1,2,3],
              [2,3,4]])
print(arr)
print('number of dim:',arr.ndim)
print('shape:',arr.shape)
print('size:',arr.size)

[[1 2 3]
 [2 3 4]]
number of dim: 2
shape: (2, 3)
size: 6


In [4]:
a=np.array([2,23,4],dtype=np.float32)
print(a.dtype)

float32


In [9]:
# 2.创建
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.empty((2,2))

array([[9.52773673e-312, 9.52755979e-312],
       [9.52755982e-312, 9.52755983e-312]])

In [26]:
np.random.random((2,4))

array([[0.52585504, 0.59959825, 0.94037316, 0.59870569],
       [0.01924337, 0.4443937 , 0.44267716, 0.28195061]])

In [10]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [11]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
np.arange(12).reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [18]:
# 3 数、矩阵的计算/  +-*/  
#               /  sin cos tan
#               /  < >  
#               /  max min sum 
#               / 计算索引
#               /mean median cumsum diff nonzero sort clip transpose
a=np.array([10,20,30,40])
b=np.arange(4)
c=a/b
print(c)

[        inf 20.         15.         13.33333333]


C:\Users\V9876\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.


In [21]:
np.cos(0)

1.0

In [22]:
print(a>30)

[False False False  True]


In [24]:
a=np.array([[1,1],
            [0,1]])
b=np.arange(4).reshape((2,2))
c=np.dot(a,b)
d=a*b
print('矩阵乘法：\n',c)
print('数的乘法：\n',d)

矩阵乘法：
 [[2 4]
 [2 3]]
数的乘法：
 [[0 1]
 [0 3]]


In [28]:
a=np.random.random((2,3))
print(a)
print(np.sum(a,axis=1))
print(np.max(a,axis=0))
print(np.min(a,axis=0))

[[0.26737975 0.54270119 0.65103793]
 [0.07889078 0.25179026 0.26240155]]
[1.46111887 0.5930826 ]
[0.26737975 0.54270119 0.65103793]
[0.07889078 0.25179026 0.26240155]


In [41]:
A=np.arange(10,22).reshape((3,4))
print(A)
print(np.argmin(A,axis=0))
print(np.argmax(A))
print('mean:',np.mean(A))
print('median:',np.median(A))
print('cumsum:',np.cumsum(A))
print('diff:\n',np.diff(A))
print('nonzero:',np.nonzero(A))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[0 0 0 0]
11
mean: 15.5
median: 15.5
cumsum: [ 10  21  33  46  60  75  91 108 126 145 165 186]
diff:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
nonzero: (array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


In [47]:
B=np.arange(22,10,-1).reshape((3,4))
print('B:\n',B)
print('sortB:\n',np.sort(B))
print('Btranspose:\n',np.transpose(B))
print('Bclip:\n',np.clip(B,15,19))

B:
 [[22 21 20 19]
 [18 17 16 15]
 [14 13 12 11]]
sortB:
 [[19 20 21 22]
 [15 16 17 18]
 [11 12 13 14]]
Btranspose:
 [[22 18 14]
 [21 17 13]
 [20 16 12]
 [19 15 11]]
Bclip:
 [[19 19 19 19]
 [18 17 16 15]
 [15 15 15 15]]


In [50]:
for i in B.flat:
    print(i)

22
21
20
19
18
17
16
15
14
13
12
11


In [53]:
# 4.合并

a=np.array([1,1,1])
b=np.array([2,2,2])
c=np.vstack((a,b))
d=np.hstack((a,b))
print(c)
print(d)

[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]


In [55]:
print(a[:,np.newaxis])

[[1]
 [1]
 [1]]


In [59]:
# 5.分割
A=np.arange(10,22).reshape((3,4))
print(A)
#等量分割
# 不等量分割
print(np.split(A,3,axis=0))
print(np.array_split(A,3,axis=0))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[array([[10, 11, 12, 13]]), array([[14, 15, 16, 17]]), array([[18, 19, 20, 21]])]
[array([[10, 11, 12, 13]]), array([[14, 15, 16, 17]]), array([[18, 19, 20, 21]])]


In [63]:
print(A)
print(np.vsplit(A,3))
print(np.hsplit(A,2))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[array([[10, 11, 12, 13]]), array([[14, 15, 16, 17]]), array([[18, 19, 20, 21]])]
[array([[10, 11],
       [14, 15],
       [18, 19]]), array([[12, 13],
       [16, 17],
       [20, 21]])]


In [65]:
# 6.赋值
a=[1,2,3,4]
b=a
a[0]=11
print(b)

[11, 2, 3, 4]


In [68]:
a=[1,2,3,4]
b=a.copy()
a[0]=11
print(b)

[1, 2, 3, 4]
